# Generated by Django 4.1.7 on 2023-04-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="charge",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
