# Generated by Django 4.1.7 on 2023-04-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_charge_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="usercredit",
            name="credit",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
